a = input("taper le premier nombre: ") 
b = input("taper le deuxieme nombre: ")
som = int(a) + int(b)
print("la somme est: ", som)
soust = int(a) - int(b)
print("la difference est: ", soust)
mult = int(a) * int(b)
print("le produit est: ", mult)
div = int(a) // int(b)
print("le quotient est: ", div)
pourcent = int(a) % int(b)
print("le reste de la division est: ", pourcent)
puissance = int(a) ** int(b)
print(a, "a la puissance", b, "est: ", puissance)
