print("Taper le premier nombre: ")
a = input()
print("Taper le deuxieme nombre: ")
b = input()
print("Taper le troisieme nombre: ")
c = input()
print("Taper le quatrieme nombre: ")
d = input()
print("Le nombre forme est: ", a + b + c + d)